### ISSUE TITLE
Travis test formatter premature folding

### ISSUE THREAD

**Issue by peteruhnak** [hpi-swa/smalltalkCI#56] opened 2016-02-12 12:54 UTC
I love the new travis formatter, makes for a very nice output :+1:

However I've noticed that when a test fails it collapses everything below it; shouldn't it just collapse the one failing test?

build: https://travis-ci.org/dynacase/class-editor/builds/108775996#L770

open
![travis-open](https://cloud.githubusercontent.com/assets/1276328/13007362/19bc0b44-d190-11e5-98ff-96e3f3917767.png)

collapsed
![travis-close](https://cloud.githubusercontent.com/assets/1276328/13007367/1d8deb34-d190-11e5-8707-71a59de16a20.png)

**Comment by fniephaus** [comment] 2016-02-12 19:11
Yes, that's a bug. I'll fix it this weekend :smiley:

**Comment by fniephaus** [comment] 2016-02-14 15:05
@peteruhnak please reopen this if https://github.com/hpi-swa/smalltalkCI/commit/25ece9fde33aaf9acc6c3aa80b18363157423445 hasn't resolved the problem.

**Comment by peteruhnak** [comment] 2016-02-14 15:29
@fniephaus now the folding instructions are visible in the output and not applied https://travis-ci.org/dynacase/class-editor#L766

**Comment by peteruhnak** [comment] 2016-02-14 15:30
Also I can't reopen the issue (“*you cannot re-open your own issues if a repo collaborator closed them*”)

**Comment by fniephaus** [comment] 2016-02-14 18:26
I didn't know it's impossible to reopen issues when a repo collaborator closed it. Sorry about that :(

Just pushed a fix, hopefully this will do.

**Comment by peteruhnak** [comment] 2016-02-14 18:39
The folding now works, but the output of the failing tests appears to be duplicated.
https://travis-ci.org/dynacase/class-editor/builds/109171399#L766
The lines L766 and L777 are the same error report.

**Comment by fniephaus** [comment] 2016-02-14 19:32
It's actually been printed once, but Travis somehow didn't like the formatting and displays everything twice. I've pushed another update.
Feel free to close the bug if it works ;)

**Comment by peteruhnak** [comment] 2016-02-14 20:01
Excellent, now it works as one would expect https://travis-ci.org/dynacase/class-editor#L1321, thanks!

**Comment by fniephaus** [comment] 2016-02-14 20:07
It's still there, but now I know what the problem is!

**Comment by peteruhnak** [comment] 2016-02-14 20:39
How about now https://travis-ci.org/dynacase/class-editor/builds/109171399#L1320 ?

**Comment by fniephaus** [comment] 2016-02-14 23:51
That's it, thanks! `travis_fold`s require unique identifiers and that was the problem.

**Closed by fniephaus** 2016-02-14 23:51 UTC
Labels: bug
