### ISSUE TITLE
Projects in GitHub won't load in Pharo 7 on Travis

### ISSUE THREAD

**Issue by gcotelli** [hpi-swa/smalltalkCI#306] opened 2017-07-14 12:22 UTC
Hi,

I'm having this error:

```
Loading baseline of BaselineOfWillow...Creating iceberg-metacello adapter for: github://ba-st/RenoirSt:master/source

LGit_GIT_ERROR: error authenticating: no auth sock variable
```
Check the full log output in:
https://travis-ci.org/ba-st/Willow/jobs/253572685

The build works Ok por Pharo 5/6 , but fails on Pharo 7 (running in Linux)

**Comment by theseion** [comment] 2017-07-14 13:40
This is probably an Iceberg / LibGit2 problem, not specific to smalltalkCI. Can you reproduce the problem when you evaluate the load instructions manually?

**Comment by gcotelli** [comment] 2017-07-14 14:10
Works ok in my local machine with a recently downloaded image and VM:

Image
-----
/home/gcotelli/Pharo/Pharo7-32/Pharo.image
Pharo7.0SNAPSHOT
Latest update: #0
Unnamed

Virtual Machine
---------------
/home/gcotelli/Pharo/Pharo7-32/pharo-vm/lib/pharo/5.0-201707132359/pharo
CoInterpreter VMMaker.oscog-eem.2253 uuid: 45202565-6d57-4e4b-812f-a8eea4685e21 Jul 14 2017
StackToRegisterMappingCogit VMMaker.oscog-eem.2252 uuid: 2f3e9b0e-ecd3-4adf-b092-cce2e2587a5c Jul 14 2017
VM: 201707132359 https://github.com/OpenSmalltalk/opensmalltalk-vm.git $ Date: Thu Jul 13 16:59:42 2017 -0700 $ Plugins: 201707132359 https://github.com/OpenSmalltalk/opensmalltalk-vm.git $

Unix built on Jul 14 2017 00:14:07 Compiler: 4.6.3
VMMaker versionString VM: 201707132359 https://github.com/OpenSmalltalk/opensmalltalk-vm.git $ Date: Thu Jul 13 16:59:42 2017 -0700 $ Plugins: 201707132359 https://github.com/OpenSmalltalk/opensmalltalk-vm.git $
CoInterpreter VMMaker.oscog-eem.2253 uuid: 45202565-6d57-4e4b-812f-a8eea4685e21 Jul 14 2017
StackToRegisterMappingCogit VMMaker.oscog-eem.2252 uuid: 2f3e9b0e-ecd3-4adf-b092-cce2e2587a5c Jul 14 2017

**Comment by gcotelli** [comment] 2017-07-14 14:12
Maybe is something with the SSH credentials used to download?

**Comment by theseion** [comment] 2017-07-14 14:12
Thanks. We'll look into it.

**Comment by theseion** [comment] 2017-07-14 14:13
>Maybe is something with the SSH credentials used to download?
Possibly, but I don't think so. It could be a problem with libssh2 (which would suck big time because debugging libssh2 is a nightmare).

**Comment by theseion** [comment] 2017-07-17 17:29
I suppose your problem is indeed this one: https://github.com/pharo-vcs/iceberg/issues/334 (LibGit2 tries to retrieve the SSH key from the key store (e.g. ssh-agent) and fails).

What strikes me though, is that `github://` URL's did not use to be loaded with Iceberg by default. For that to happen you had to explicitly enable the Metacello integration. That has changed, apparently. I think we can fix the problem for now by disabling Metacello integration when loading with SCI.

**Comment by theseion** [comment] 2017-07-17 17:39
I've pushed a fix to the dev branch. Could you test it please?

**Comment by dionisiydk** [comment] 2017-07-17 19:00
I test it and got DNU error. You should use environment directly without globals:

```Smalltalk
disableIcebergDuring: aBlock
	| integrationEnabled |
	self class environment
		at: #Iceberg
		ifPresent: [ :iceberg |
			integrationEnabled := iceberg enableMetacelloIntegration.
			iceberg enableMetacelloIntegration: false ].
	aBlock ensure: [
		self class environment
			at: #Iceberg
			ifPresent: [ :iceberg |iceberg enableMetacelloIntegration: integrationEnabled ] ]
```

**Comment by theseion** [comment] 2017-07-17 19:05
Thanks... There's just too many ways in Pharo and Squeak to access environments and globals...

Fixed. Can you try again?

**Comment by dionisiydk** [comment] 2017-07-17 21:01
Now it works. Thank's

17 июля 2017 г. 9:06 PM пользователь "Max Leske" <notifications@github.com>
написал:

**Closed** 2017-07-18 05:25 UTC
Labels: bug, Pharo

**Comment by gcotelli** [comment] 2017-07-31 17:36
Any ETA for this to land in master ?

**Comment by fniephaus** [comment] 2017-07-31 17:45
@theseion can we merge `dev` into `master`?

**Comment by theseion** [comment] 2017-08-01 07:21
I don't see, why not.

**Comment by dionisiydk** [comment] 2017-08-01 07:45
My projects use dev branch for CI testing. They work fine

2017-08-01 9:21 GMT+02:00 Max Leske <notifications@github.com>:

> I don't see, why not.
>
>
> On 31 July 2017 at 19:45:04, Fabio Niephaus (notifications@github.com(

**Comment by fniephaus** [comment] 2017-08-01 07:59
Thanks, merging via #312.
