### ISSUE TITLE
Fuel files on github

### ISSUE THREAD

**Issue by SergeStinckwich** [hpi-swa/smalltalkCI#146] opened 2016-05-20 22:32 UTC
This would be nice to have fuel files generated by failing tests available on github after a CI run in order to have access to them more easily.

**Comment by marianopeck** [comment] 2016-05-30 17:34
Yes!!!! that we awesome. We already do this since years for Pharo CI. I can point out to @fniephaus how to grab that code. Let me know if you are interested in.

**Comment by fniephaus** [comment] 2016-05-30 17:45
What do these fuel files contain? How would they need to be accessible? As part of the Travis log or where would they be uploaded to?

**Comment by marianopeck** [comment] 2016-05-30 18:19
Hi @fniephaus 

The main problem with Travis CI in this case, is that yes, we would need to store the .fuel files. Let me summarize a bit... Fuel, (which as you know does work on Squeak too), can serialize classes, methods, closures, contexts etc etc. So, on Pharo CI (INRIA) when a test fails, we serialize the stack with Fuel (we call this `Fuel out stack`) into a binary fuel file. This serializes the LIVE stack of objects (besides the string representation of the stack). That way, you can take a Pharo image, download the fuel files of the test failures of the CI, and materialize that stack into Pharo for debugging. That will bring a debugger with the live stack in your Pharo image. 

But as you said, for this to work, the fuel files should be uploaded somewhere as AFAIK free Travis CI does not allow storage, right?

**Comment by fniephaus** [comment] 2016-05-30 18:23
Thanks for the explanation!
Yes, I'm afraid Travis CI does not offer free storage for artifacts.
However, artifacts can be uploaded to many different services as well as to a custom server.
How big can such a Fuel file be?

**Comment by marianopeck** [comment] 2016-05-30 18:27
In general they are a couple of KB or MB. But sometimes it can be more. The problem is that when you serialize the stack, it's common to serialize a big graph as the boundaries are not always very clear. In addition, for proper (correct) debugging, it's likely also need to download THE VERY same built image (just before running the test). So.. we need that space also. In Pharo CI it's like that, we have both as artifacts, the built image and the fuel files.

**Comment by fniephaus** [comment] 2016-05-30 18:33
Well, that's too bad. I'm currently working on ways to "deploy" images after a successful build, but I'm not yet sure how to deal with the storage problem. I believe Pharo CI uploads build artifacts to some custom server?

**Comment by SergeStinckwich** [comment] 2016-05-30 18:37
This is not possible to commit an artefact from Travis to github ?

**Comment by marianopeck** [comment] 2016-05-30 18:39
I am not sure, you could ask Christophe Demarey about Pharo CI. As far as I know, the artifacts are stored in the same CI server... oh.. well...there is a file server too I think... mmm

**Comment by SergeStinckwich** [comment] 2016-05-30 18:41
Apparently this is possible :

https://docs.travis-ci.com/user/deployment/releases/

**Comment by fniephaus** [comment] 2016-05-30 18:44
@SergeStinckwich the problem with GitHub releases is that this only works for tags, so you'd need to tag every commit which isn't very convenient...

**Comment by SergeStinckwich** [comment] 2016-05-30 18:47
Make sense if tags corresponds to releases.

**Comment by fniephaus** [comment] 2016-05-30 19:18
But then you don't get Fuel files and images only for releases and not for each commit.
I'm not sure if every user wants that...

**Comment by fniephaus** [comment] 2016-05-30 19:35
[bintray.com](http://bintray.com) seems to be offering free hosting for build artifacts for OSS projects.
But they only keep files for 180 days AFAIK...

**Comment by marianopeck** [comment] 2016-05-31 13:22
That looks good enough for at least some OSS projects :)
Anyway, whenever you want to take a look to the fuel export, let me know
and I point you out the correct places in the Pharo image.

Best,

On Mon, May 30, 2016 at 4:35 PM, Fabio Niephaus <notifications@github.com>
wrote:

> bintray.com seems to be offering free hosting for build artifacts for OSS
> projects.
> But they only keep files for 180 days AFAIK...
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/hpi-swa/smalltalkCI/issues/146#issuecomment-222545143>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AA_CggAOqmU6iX2I6M9KnDlMQKjUjpcuks5qGzvlgaJpZM4IjnQU>
> .
>



-- 
Mariano
http://marianopeck.wordpress.com

**Comment by SergeStinckwich** [comment] 2016-05-31 13:32
Could not find the limitation about 180 days in bintray documentation.

**Comment by fniephaus** [comment] 2016-05-31 14:24
@marianopeck how can I export fuel files for failed tests? Tests in Pharo are run [here](https://github.com/hpi-swa/smalltalkCI/blob/master/repository/SmalltalkCI-Pharo-Core.package/SmalltalkCIPharo.class/instance/runTests.st), feel free to implement fuel exporting if you have some time. I guess it'd make sense to put those files in the build directory, so the bash script could pick them up afterwards...

@SergeStinckwich it looks like you can't delete files after 180 days (see [here](https://bintray.com/docs/api/) and search for 180), but that shouldn't be a problem :)

**Comment by marianopeck** [comment] 2016-05-31 15:41
Hi @fniephaus 

Right now i cannot commit myself into implementing this into smalltalkCI, even if I would love it. Business...you know. Anyway, I wanted to write the the spots to take a look in case others may do this. You can grab a  Pharo 5.0/6.0 and check `HDTestReport serializeError: error of: aTestCase`. And from there, follow to `FuelOutStackDebugAction` where is where the magic happens .

Best,

**Comment by fniephaus** [comment] 2016-05-31 16:39
I just realized that fuel files are already exported to the project directory. So these files only need to be uploaded which leaves us with the hosting problem again...

**Comment by fniephaus** [comment] 2016-06-03 14:01
Hi @SergeStinckwich and @marianopeck,
I've just added experimental support for Bintray deployments.

First, you need to sign up for Bintray and create a [repository](https://bintray.com/docs/usermanual/uploads/uploads_creatinganewrepository.html) and one or two [packages](https://bintray.com/docs/usermanual/uploads/uploads_creatinganewpackage.html).

Then, all you have to do is to go to your project's Travis CI settings (https://travis-ci.org/{YourProject}/settings) and add the following entries:

`BINTRAY_CREDENTIALS`: `{user}:{api_key}` -> used to authenticate reqs (you can find your api_key [here](https://bintray.com/profile/edit))
`BINTRAY_RELEASE`: `{user}/{repo}/{package}` -> target package for successful builds on master
`BINTRAY_FAIL`: `{user}/{repo}/{package}` -> target package for all failed builds for all branches

You can leave one out (`BINTRAY_RELEASE` or `BINTRAY_FAIL`) if you wish.

For releases, the build artifacts are currently the image and changes files.
When a build fails, a debug.tar.gz is added that contains the JUnit XML file and fuel files if any.

Please feel free to provide any feedback you might have.

**Comment by fniephaus** [comment] 2020-09-29 14:28
Closing this in favor of #475.

**Closed by fniephaus** 2020-09-29 14:28 UTC
