### ISSUE TITLE
smalltalk_config is not working

### ISSUE THREAD

**Issue by vitormcruz** [hpi-swa/smalltalkCI#185] opened 2016-08-23 02:45 UTC
Smalltalk CI will aways look for .smalltalk.ston no matter you put smalltalk_config: in travis.yml,and it will fail if it is not there or wrongly configured.

**Comment by fniephaus** [comment] 2016-08-23 10:34
This is a duplicate of https://github.com/hpi-swa/smalltalkCI/issues/184
Do you have an example `.smalltalk.ston` file?

Unfortunately, you can't have lists with a single value in yml.
So this:

```yml
smalltalk_config:
  - my.ston
```

does not work, but this does:

```yml
smalltalk_config: my.ston
```

It's a TravisCI bug and they know about it. However, I have no idea when/if they will change this.

**Comment by vitormcruz** [comment] 2016-08-23 14:27
It does not work with a list of more than one item also. See https://travis-ci.org/vitormcruz/Katas-and-Challenges-ST, I have tried a number of stuff, it always as for .smalltalk.ston.

**Comment by fniephaus** [comment] 2016-08-23 21:58
Yes, you are right, @vitormcruz.
I've opened an issue in Travis' issue tracker (see https://github.com/travis-ci/travis-ci/issues/6514).

**Comment by vitormcruz** [comment] 2016-08-23 23:59
Thank you!

**Comment by fniephaus** [comment] 2018-05-10 13:53
According to https://github.com/travis-ci/travis-core/pull/567#issuecomment-328791745, the folks at Travis have finally pushed a fix for this. I just tried out something like the below and can confirm that it's working now:
```yml
...
smalltalk_config:
  - a.ston
  - b.ston
...
```

**Closed by fniephaus** 2018-05-10 13:53 UTC
Labels: bug
