### ISSUE TITLE
Jobs testing Pharo alpha VM dont work because --nodisplay is an unknown option now

### ISSUE THREAD

**Issue by gcotelli** [hpi-swa/smalltalkCI#443] opened 2019-10-03 15:56 UTC
Aparently `--nodisplay` is an unknown option for the VM now.

```
Downloading and extracting smalltalkCI
install

0.00s$ [[ ! -d ${SMALLTALK_CI_CACHE} ]] || mv ${SMALLTALK_CI_CACHE} $(pwd)

4.86s$ bin/smalltalkci --self-test

Preparing folders...

Build folder already exists at /home/travis/build/hpi-swa/smalltalkCI/_builds.
set_rtprio_limit

0.11sRaising real-time priority for OpenSmalltalk VMs with threaded heartbeat...

Starting Pharo build...
download_image

2.68sDownloading Pharo32-alpha image...

Preparing Pharo image...
download_vm

1.44sDownloading Pharo32-alpha vm...

unknown option: --nodisplay
```

**Comment by fniephaus** [comment] 2019-10-14 18:29
I have noticed this, too. But I have no idea why `--nodisplay` has been dropped. Any help would be appreciated!

**Comment by theseion** [comment] 2019-11-17 11:04
This is a side-effect of https://github.com/OpenSmalltalk/opensmalltalk-vm/issues/433. The zeroconf VM hasn't been updated yet to use the Clang build. That should happen automatically, if I'm not mistaken. @estebanlm can you confirm or update the zeroconf for linux64x64?

**Comment by theseion** [comment] 2019-12-24 09:39
@estebanlm SmalltalkCI has been unable to run builds of Pharo 8 since at least September. At least for Fuel that means I can't release an updated version for Pharo 8 / 9 or Squeak 5.3+. All I would need for now are updated zeroconf builds that use Nicola's fix for building with Clang instead of GCC. We have verified that the Clang builds work.

**Comment by estebanlm** [comment] 2020-01-03 19:21
sorry, I lost this. 
I will check it next week (on holidays now)

**Comment by estebanlm** [comment] 2020-01-09 07:41
mmm... problem is more complicated than that. 
(by the way, this has nothing to do directly with Pharo, except by the fact we dropped --nodisplay usage)
Main build of osvm is not working properly since some months. When you try to use alpha vm you actually use the latest build, which is broken (on mac at least, hopefully not the others since break was because of Metal introduction).

What I do not understand is where the --nodisplay comes from since zeroconf does not uses it :P

**Comment by estebanlm** [comment] 2020-01-09 09:18
In a debian 64bit, exciting this: 
```Smalltalk
./bin/smalltalkci -s "Pharo64-stable" ../Fuel/.corewithextras.ston
./bin/smalltalkci -s "Pharo64-alpha" ../Fuel/.corewithextras.ston
```
works.
Checking on 32bit.

**Comment by theseion** [comment] 2020-01-09 09:42
> What I do not understand is where the --nodisplay comes from since zeroconf does not uses it :P
It's in the `pharo` script for starting the image. Try this on a linux machine:
`curl get.pharo.org/64/80+vmLatest | bash; cat pharo`

**Comment by theseion** [comment] 2020-01-09 09:49
You're right, it does work now, just not on Travis. @fniephaus do you maybe need to update the version of SmalltalkCI that runs on Travis?

**Comment by estebanlm** [comment] 2020-01-09 20:56
@theseion I was about to ping you about this :)
I do not understands what happens because everything seems to work.

**Comment by fniephaus** [comment] 2020-01-09 21:00
> You're right, it does work now, just not on Travis. @fniephaus do you maybe need to update the version of SmalltalkCI that runs on Travis?

Mh, I don't think so. Could you please restart your builds?

**Comment by theseion** [comment] 2020-01-09 21:01
I can but I doubt that will change anything. They run automatically every week... Let's try.

**Comment by theseion** [comment] 2020-01-09 21:04
Um... Ok... so they appear to work now... Something must have changed because 4 days ago they still failed.

**Comment by fniephaus** [comment] 2020-01-09 21:07
Great, good to know! The VMs are pulled directly from Pharo servers, so nothing needs to be updated on the Travis CI side of things.

**Comment by fniephaus** [comment] 2020-01-10 12:00
Looks like the problem is still present in `Pharo32-alpha` builds. See https://travis-ci.org/hpi-swa/smalltalkCI/jobs/634956829#L334. @estebanlm could you please have a look?

**Comment by theseion** [comment] 2020-01-11 10:40
This is getting weird... Now the same build I checked yesterday fails again with the `--nodisplay` error...

**Comment by fniephaus** [comment] 2020-01-11 10:50
None of this is in smalltalkCI's control, it must be fixed on the Pharo side. It's unfortunate that this long-standing issue is getting so little attention. :(

**Comment by theseion** [comment] 2020-01-11 16:42
@estebanlm It looks to me like the change you initially made to the zero conf script did indeed fix the problem. Why did you revert the change?

**Comment by estebanlm** [comment] 2020-01-13 15:29
because it didn't work, what I did was not what created the problem, as I think. 
I will re-submit the revert, just in case.

**Comment by theseion** [comment] 2020-01-20 20:37
The error message has changed:
>/home/travis/smalltalkCI-master/_cache/vms/Pharo64-alpha/pharo-vm/lib/pharo/5.0-/pharo: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /home/travis/smalltalkCI-master/_cache/vms/Pharo64-alpha/pharo-vm/lib/pharo/5.0-/pharo)

**Comment by theseion** [comment] 2020-03-07 20:11
I'll go ahead and close this. The issue appears to be resolved.

**Closed by theseion** 2020-03-07 20:11 UTC
Labels: Pharo, requires-external-changes
