### ISSUE TITLE
How to tell which smalltalk_config is being used

### ISSUE THREAD

**Issue by dalehenrich** [hpi-swa/smalltalkCI#128] opened 2016-04-12 23:25 UTC
This [build](https://travis-ci.org/SeasideSt/Seaside/jobs/122655950) and this [build](https://travis-ci.org/SeasideSt/Seaside/jobs/122655949) were launched using different config files, but I can't tell which build is which by looking at travis ... 

In case it matters, here is the `.travis.yml` fille:

```
language: smalltalk
sudo: false

smalltalk:
  - Pharo-5.0
#  - Pharo-4.0
#  - Pharo-3.0
#  - Squeak-4.5
  - Squeak-5.0
#  - GemStone-3.1.0.6
#  - GemStone-3.2.14
  - GemStone-3.3.0

smalltalk_config: .smalltalk.ston

cache:
  directories:
    - $SMALLTALK_CI_CACHE

matrix:
  include:
    - smalltalk: 
        - GemStone-3.3.0
      smalltalk_config:
        - .smalltalk_gs_all.ston
```

**Comment by fniephaus** [comment] 2016-04-13 09:05
https://github.com/travis-ci/travis-core/pull/528#event-625376984 wasn't merged yet which is why it didn't work, but it should now:
https://travis-ci.org/hpi-swa/smalltalkCI/builds/122732127

The value is stored in `$TRAVIS_SMALLTALK_CONFIG` (see [here](https://github.com/travis-ci/travis-build/blob/94ba5849c6f11c95135848bd97a43f16240f149a/lib/travis/build/script/smalltalk.rb#L49)).

Please close this issue if this is working for you now...

**Comment by dalehenrich** [comment] 2016-04-13 12:44
Actually my question was how to tell which config is being used from the GUI ... for example, can you tell which config is being used in the run that I referenced?

**Comment by dalehenrich** [comment] 2016-04-13 12:58
From the browse interface it seems to be impossible to tell which config is being used .... without the error message from #129 I wouldn't have know which config was being used ..

**Comment by fniephaus** [comment] 2016-04-13 13:01
It appears to be a well-known problem:
Travis has merged https://github.com/travis-ci/travis-core/pull/528, but it's not yet in production.

Bear with me, it might work tomorrow! The UI should also reflect those changes, but we'll see.

**Comment by dalehenrich** [comment] 2016-04-13 13:16
I think these are very useful features -- which is why I used it immediately out of the gate -- the list of projects stacked up behind my work :) -- and I submit bugs, because I want to see this work succeed so I will be patient and let the fixes work their way through the system :)

I appreciate your effort!

**Comment by fniephaus** [comment] 2016-04-14 12:51
Matrix expansion now works as intended and the config name for a build is stored in `$TRAVIS_SMALLTALK_CONFIG` successfully. Unfortunately, the UI does not show which config file is being used, I'll have a chat with Travis about this...

**Comment by fniephaus** [comment] 2016-04-14 13:19
@chistopher knows how to fix this :)

**Comment by Nef10** [comment] 2016-04-21 07:49
@dalehenrich @fniephaus works now

**Comment by fniephaus** [comment] 2016-04-21 08:02
Thanks!

**Closed by fniephaus** 2016-04-21 08:02 UTC
Labels: bug
