### ISSUE TITLE
Support for additional coverage services

### ISSUE THREAD

**Issue by gcotelli** [hpi-swa/smalltalkCI#454] opened 2020-04-27 13:43 UTC
@fniephaus moved from #453 to discuss it better: 
> Happy to add support for other coverage providers if we can. Uploading coverage results is relatively simple and I think something smalltalkCI should help with if possible. I'd like to avoid to support too many env variables, how about we add an #service option to the #coverage dict of  SmalltalkCISpec?
> Example
>
> SmalltalkCISpec {
>   ...
>   #testing : {
>     ...
>     #coverage : {
>       #classes : [ #ClassToCover, #'ClassToCover class' ],
>       #service : #codecov
>     }
>   }
> }
> 
> At the moment, supported services could be #coveralls, #codecov, and #local (for the coverage results file only). If we set the default to #coveralls, we would even be backward compatible.
> 
> What do you think?

I think there are 2 orthogonal issues here. One is the format of the exported coverage file (now it's always exported in coveralls JSON format) and I think that configuring it in SmalltalkCISpec will help with that if we want to support multiple export formats.
At least Codecov is capable of understanding the coveralls export format so we don't need to make changes per-se on the export code to support this service.
The second one is the service provider to which upload the exported coverage files. Now it is assumed that if you enabled coverage you want to upload it to coveralls and this is done in the shell scripts not in Smalltalk code. If I understand it right the info in SmalltalkCISpec is not available in the shell commands so I don't know how changing this spec will help in selecting the right provider to upload.

It always feels a bit strange to me that the smalltalkCI scripts per se are the ones uploading the files to the coverage services. For example for CodeCov if you're using GitHub actions you can re-use the official upload action and just provide the file name to upload in a later step. 

Maybe we can separate the upload code in a different shell script and add two command line options:
- One option will disable the automatic coverage upload inside the smalltalkCI script, so people reusing for example CodeCov GitHub actions can disable the automatic upload and let later steps take care of the upload.
- The other option will configure the coverage service provider, so if the automatic coverage upload is enabled this option is used to choose the service to call by invoking the chosen upload script.
- By default the automatic coverage upload will be `enabled` and the service provider will be `coveralls` to maintain backwards compatibility.

What do you think?

**Comment by fniephaus** [comment] 2020-04-27 14:02
I prefer configuration to be as easy as possible. So setting the coverage provider once (in the `.smalltalk.ston`) should be enough. We can extract that value from Bash, I think we're already doing something like this somewhere else already, too. Having the provider in the SmalltalkCISpec will allow us to add support for other formats in the future.
We could also add another option `#auto_upload` and enabled it by default. That way, we could also add an `smalltalkci --upload-coverage` hook, that users can call later in the build process. Is this what you had in mind?
Should we also make the coverage file name configurable?

**Comment by gcotelli** [comment] 2020-04-27 14:28
> I prefer configuration to be as easy as possible. So setting the coverage provider once (in the `.smalltalk.ston`) should be enough. We can extract that value from Bash, I think we're already doing something like this somewhere else already, too. Having the provider in the SmalltalkCISpec will allow us to add support for other formats in the future.

Yes, If we can extract that info form `.smalltak.ston` using bash then it's Ok. It is better that way.

> We could also add another option `#auto_upload` and enabled it by default. That way, we could also add an `smalltalkci --upload-coverage` hook, that users can call later in the build process. Is this what you had in mind?

Yes, so the user has the option to use auto-upload, call it in another step or let the GitHub action doit for them (like the case of CodeCov that only needs to know the file name)

> Should we also make the coverage file name configurable?

The only thing we need to provide is access to the coverage file name at least for the services I know. The specific file name doesn't matter.

**Comment by gcotelli** [comment] 2020-04-27 15:22
Just to summarize the needed changes:
1. Update `SmalltalkCISpec` coverage section to support:
```
SmalltalkCISpec {
...
  #testing : {
  ...
    #coverage : {
      #classes : [ #ClassToCover, #'ClassToCover class' ],
      ...
      #service : #codecov , 
      #auto_upload: true
    }
  }
}
```
`#service` will support `#coveralls`, `#codecov` and `#local`. If not defined it will default to `#coveralls` if running on a TravisCI/AppVeyor, and to #local if not. `#local` meaning it will not upload the file anywhere. This is to keep backwards compatibility.

2. Implement handling for `#codecov` to upload the generated files
3. `#auto_upload` is a boolean defaulting to true. If enabled will attempt to upload the generated coverage file to the service declared in `#service` during the standard smalltalkCI invocation. If disabled just will keep the file on disk.
4. Add `--upload-coverage` hook to `smalltalkCI` to manually trigget the coverage file upload

**Comment by gcotelli** [comment] 2020-04-27 15:24
@fniephaus if we're ok with this changes I can give it a try.

**Comment by gcotelli** [comment] 2020-04-27 22:12
@fniephaus I've checked the bash files and the only place I found doing something with the .ston files is in helpers.sh but it only checks for the existence of a line including `#loading`:
`grep -Fq "#loading" "${config_ston}"`
But I don't found any value extraction, and I think it will very tricky to do it in bash because we need to not only get the `#service` value but it also must be contained in the coverage section.

Any help here is welcomed. I'm by far no bash expert.

**Comment by fniephaus** [comment] 2020-04-27 22:40
Yes, that could indeed be tricky. The image could export the ston as bash file, which can be read after the build. Not sure this is a good solution in general. I'll have to think about this some more

**Comment by gcotelli** [comment] 2020-04-27 23:06
Maybe we can export some kind of .env file from the image and read it as environment variables to be used later in the script doing the upload. But I'm all ears here, so if you have a better idea let me know. I will wait for your feedback before proceeding.

**Comment by gcotelli** [comment] 2020-04-30 12:49
@fniephaus any idea on how we can proceed?

**Comment by gcotelli** [comment] 2020-05-02 13:48
LGTM. I will give it a try.

**Comment by SabineMa** [comment] 2020-05-14 17:08
We use Gitlab. When I run smalltalkCI with a definition for #testing and #coverage in the .smalltalk.ston, then my file coveralls_results.json looks like this.

{"service_name":"unknown","git":{"branch":"unknown","head":{"author_name":"\n\u001B[1m\u001B[33mError with status code 128:\u001B[0m\n348 git_log ...

Do I understand right that 
1.) currently it is not possible to create a coverage file without having GitHub and coveralls.io account?
2.) with this issue and the #local parameter this would be possible?
-> this would be great

**Comment by gcotelli** [comment] 2020-05-14 17:59
@SabineMa there are two different things. One is the format of the coverage file. Right now the only export format supported is the Coveralls one. 
The other thing is the coverage reporting service per-se. Other services like CodeCov (codecov.io) for example are capable of reading these format and showing correctly the coverage report. This last step is the thing we're working on this issue. 
So when the related PR get merged the user will have control over two things: 
1. The user can tell smallatlkCI to not try to upload automatically the exported file to the coverage service (for example we're using CodeCov now in our repositories at github.com/ba-st but the upload is done in a later step using the official GitHub action)
2. If you want smalltalkCI to automatically upload the exported file to the coverage service, now you can select Coveralls or CodeCov as a target service.

Regarding your questions:
1. When the PR gets merged you can create the coverage file without having a GitHub/Coveralls/CodeCov account, but the format will be the one expected by the Coveralls API.
2. As your example is showing the basic template used for creating the coverage file seems to be not created right for Gitlab (this depends on some env variables so it's totally plausible).

So I think it depends on what are you trying to accomplish. If Gitlab provides some kind of "coverage service" or some way to show coverage reports on it and it's capable of reading the Coveralls export format we need to open a new issue so the basic template is generated Ok for Gitlab. This should be pretty straight forward to fix.
If Gitlab supports other coverage format then we will need Smalltalk code to generate that format.

**Comment by SabineMa** [comment] 2020-05-14 21:14
Hi Gabriel,

what I want to have at the end, is a [coverage badge  ](https://docs.gitlab.com/ee/user/project/badges.html) in my Gitlab repos readme and in the pipelines.

From the doc [here](https://docs.gitlab.com/ee/ci/pipelines/settings.html#test-coverage-report-badge). I see  "GitLab makes it possible to define the regular expression for coverage report, that each job log will be matched against." 

So I assume that I will only need some output like

"test coverage: xx%" 

in the job log. With a regEx I can then create the badge.

I will experiment with this and come back to you with concrete informations.

Thank you for the fast answer to my questions.

**Comment by gcotelli** [comment] 2020-05-14 21:59
Apparently the supported format is not the same: https://docs.gitlab.com/ee/user/project/merge_requests/test_coverage_visualization.html#enabling-the-feature
The docs mention cobertura (XML) format, so I think you will need a different exporter. I suggest to open a new issue and if you have more info on the format maybe it's possible to implement it without too much effort.

**Comment by SabineMa** [comment] 2020-07-03 07:38
Hi Gabriel, Hi Fabio,

it is as you say, Gitlab needs corbertura format. I don't have time to go deeper. Perhaps some day anyone can create such a reporter. Then, coverage would be available for gitlab users, too.

More info is in the Link you provided:
https://docs.gitlab.com/ee/user/project/merge_requests/test_coverage_visualization.html#enabling-the-feature 

regards
Sabine

**Comment by fniephaus** [comment] 2020-08-03 12:08
Hi Sabine,
It seems that this Cobertura XML format is not documented. If you come across a documentation, that'd be helpful. At least CodeCov supports the format as well.

**Comment by SabineMa** [comment] 2020-08-03 12:16
Hi Fabio,

I am very busy currently. As soon as I have time I will come back!

Sabine

**Comment by MrModder** [comment] 2020-08-26 15:44
@fniephaus and I have decided to further explore the possibility of supporting more Coverage formats.
Currently we aim to support LCOV, as it is supported by both CodeCov and Coveralls and easy to implement.
LCOV also allows you to generate a fully interactable HTML report using the `genhtml` Linux tool, if you don't want to use a coverage service at all.
A conversion tool from LCOV to Cobertura XML also exists ( https://github.com/eriwen/lcov-to-cobertura-xml ).

However we think it hard to maintain and not strictly necessary to support uploading to all coverage services. CodeCov already provides an uploading tool for this purpose, and Coveralls supports uploading LCOV data from Github actions with [their own action](https://github.com/marketplace/actions/coveralls-github-action).
As long as usage of these uploaders is well documented, it enables SmalltalkCI to be supported on a wide range of CI platforms and coverage services.

I will work on implementing LCOV in the coming days/weeks. Feedback and other suggestions are welcome.
The tracking issue for this is #464

**Comment by MrModder** [comment] 2020-09-05 19:52
Now that #466 is merged, this issue could be closed IMHO.
It's not possible to disable Coveralls uploading at the moment, but I don't really see a use case for using coveralls format over LCOV and not uploading to Coveralls.
@gcotelli do you agree that this issue can be closed?

@SabineMa , have you tried converting LCOV to Cobertura XML with GitLab CI?

**Comment by SabineMa** [comment] 2020-09-06 14:37
Hi
I am in holidays, will try asap and come back to you. Thank you for your
work!!
Regards
Sabine


Leon Matthes <notifications@github.com> schrieb am Sa. 5. Sept. 2020 um
21:52:

**Comment by fniephaus** [comment] 2020-09-14 08:00
I'm going to close this for now, but please feel free to reopen the issue, @gcotelli and @SabineMa.

**Closed by fniephaus** 2020-09-14 08:00 UTC
Labels: coverage, enhancement

**Comment by SabineMa** [comment] 2020-09-14 12:51
I was already playing around but my lcov file was always empty. I have to find out the reason. I have other issues now but I have this on my stack and will come back with more information. Thank you so far for you work.

**Comment by MrModder** [comment] 2020-09-30 13:46
> I was already playing around but my lcov file was always empty. I have to find out the reason. I have other issues now but I have this on my stack and will come back with more information. Thank you so far for you work.

What happens if you use Coveralls format? Is the coverage file also empty?
That could help pin down the problem. Lcov and Coveralls use the same internal coverage, just write it in different ways.

**Comment by gcotelli** [comment] 2020-09-30 19:29
I've tried using the LCOV file and upload it to codecov and it looks like it is working.

**Comment by SabineMa** [comment] 2020-09-30 20:28
> > I was already playing around but my lcov file was always empty. I have to find out the reason. I have other issues now but I have this on my stack and will come back with more information. Thank you so far for you work.
> 
> What happens if you use Coveralls format? Is the coverage file also empty?
> That could help pin down the problem. Lcov and Coveralls use the same internal coverage, just write it in different ways.

The reason for the lcov file being empty was this issue:
https://github.com/hpi-swa/smalltalkCI/issues/476

when covering only one class, the lcov file is written.

**Comment by SabineMa** [comment] 2020-10-08 09:05
Hi @gcotelli , @MrModder , @fniephaus 

we had some time to have a look and I report the experiences here. No problem that the issue is closed, I refer the open issues here.

What we did:

a) run our Gitlab pipeline with StCi with creation of lcov.info file.
2) Then we integrated https://pypi.org/project/pycobertura/ in the pipeline
c) pycobertura creates a cobertura file from the lcov file.
d) pycobertura creates a html file with a report for viewing the coverage

and from that we now have:
1.) a coverage badge for the pipeline in Gitlab
2.) have the html report as an artifact of the pipeline

While creating this, we found 2 issues

https://github.com/hpi-swa/smalltalkCI/issues/477 (this issue prevents us from running all our test cases, we can currently only use a small amount of our tests)
https://github.com/hpi-swa/smalltalkCI/issues/476 (not a problem for us currently)

What we do not yet have (no time) is see the coverage in the code of gitlab as described here: https://docs.gitlab.com/ee/user/project/merge_requests/test_coverage_visualization.html

**Comment by MrModder** [comment] 2020-10-10 18:55
> #477 (this issue prevents us from running all our test cases, we can currently only use a small amount of our tests)
> #476 (not a problem for us currently)

Good to see that apart from some general coverage problems the LCOV+Cobertura pipeline is working for Gitlab! :+1:
LCOV can actually also generate an HTML report for you using the `genhtml` command.

I commented on the new issues separately (The issue numbers seem to be flipped around in your comment though, #476 is the actual problem, right?).

**Comment by SabineMa** [comment] 2020-10-11 19:43
@MrModder Hi Leon, thx for answering. Sorry, you are right, I flipped them by mistake. I will also answer in the issues.

**Comment by TiredFalcon** [comment] 2021-01-27 11:02
Hello everyone,
I'm also setting up CI with GitLab, and I followed this thread to understand how to do it.

> pycobertura creates a cobertura file from the lcov file.  

@SabineMa you mentioned using `pycobertura` to convert `lcov` to generate the Cobertura XML.
I'm reading their docs but I can't seem to find how to do that. How did you do it?

**Comment by SabineMa** [comment] 2021-01-27 11:52
Hi @TiredFalcon 
because of other issues more urgent we did not proceed with coverage but the conversion seems to work . We use the following script:

```
cd /usr/local/bin
python3 lcov_cobertura.py coverage.info
pip3 install pycobertura
pycobertura show /usr/local/bin/coverage.xml
pycobertura show --format html --output /usr/local/bin/coverage.html /usr/local/bin/coverage.xml
```

**Comment by TiredFalcon** [comment] 2021-01-27 16:05
Thank you @SabineMa, I ended up using also the pip package for `lcov_cobertura`, and everything works fine!

**Comment by fniephaus** [comment] 2021-01-27 16:11
Do you mind sharing that part of your setup? Maybe even add something to the docs

**Comment by TiredFalcon** [comment] 2021-01-27 16:14
@fniephaus I'll create a PR and work on it this weekend

**Comment by fniephaus** [comment] 2021-01-27 16:15
Excellent, thanks!
