### ISSUE TITLE
Add the latest Pharo VM option

### ISSUE THREAD

**Issue by JurajKubelka** [hpi-swa/smalltalkCI#274] opened 2017-04-21 13:02 UTC
Hi!

Is it possible, or does it make sense to add also the latest Pharo VM option? 
```
curl get.pharo.org/vmLatest60 | bash
```

I am asking for this, because the current Pharo 6 VM has a bug, that was already fixed, but not integrated to the stable VM, see [vm-dev post](http://forum.world.st/Pharo-6-Segmentation-fault-on-Travis-OS-X-tt4942756.html). And this may happen regularly for the Pharo development version. Does it make sense? 

Another suggestion is to add Pharo 64bit support, see http://get.pharo.org/64/

**Comment by fniephaus** [comment] 2017-04-21 13:13
Hi @JurajKubelka,
Yes, both absolutely makes sense and I believe your request is related to #269.
I am planning to split up the image and vm selection, so that it is possible to select a specific vm via a `smalltalk_vm` key in your `.travis.yml`.
However, I still haven't made any progress on this and it unfortunately requires to update parts of
Travis CI's code base which usually take a couple of days to be merged and deployed.
Nonetheless, the change to smalltalkCI can be made now and then you'd be able to use the new feature by temporarily overriding `script:` in your Travis config.
The problem is, I'm currently writing my master's thesis and don't really have much time at the moment, so it could probably take some time. On the other hand, I'm always happy to accept contributions if you are willing to take a look at this.

**Comment by JurajKubelka** [comment] 2017-04-21 14:03
Hi @fniephaus,

Yes, it is similar. #269 mentions a VM that works only on Linux. But yes, this is the similar request.
I will check if I can do a contribution on this :-)

**Closed** 2020-06-24 13:37 UTC
Labels: enhancement

**Comment by fniephaus** [comment] 2020-06-24 13:39
Has this been resolved, @JurajKubelka?

**Comment by JurajKubelka** [comment] 2020-06-26 14:11
Hi @fniephaus: I do not know. I guess yes, considering the #276. I closed it because it is too old. If it is really important to someone, it can be reopened. What do you think?

**Comment by fniephaus** [comment] 2020-06-26 14:55
Sure! Just wanted to know why you close the issue. Thanks!
