### ISSUE TITLE
Support of 64bit Pharo image

### ISSUE THREAD

**Issue by Uko** [hpi-swa/smalltalkCI#286] opened 2017-06-28 07:08 UTC
It would be nice to have a support for Pharo 64bit image & VM.

Image: http://files.pharo.org/get-files/60/pharo64.zip
VM:
 - http://files.pharo.org/get-files/60/pharo64-linux-threaded-stable.zip
 - http://files.pharo.org/get-files/60/pharo64-mac-stable.zip

The same applies to the 7.0 version

**Comment by macta** [comment] 2017-07-06 22:43
Yes - I've hit this one too

**Comment by fniephaus** [comment] 2017-07-07 04:34
What packages are required to run a Pharo 64bit vm on Precise/Trusty?

**Comment by Uko** [comment] 2017-07-07 08:45
Ah, right, there should be required libraries… I think that with 64 bits it has to be easier than 32. I will ask people who use Linux

**Comment by fniephaus** [comment] 2017-07-07 16:39
Looks like no additional packages need to be installed on Travis machines? :)

**Comment by estebanlm** [comment] 2017-07-07 16:48
yes, probably. 
maybe cairo but I think is already there.

Esteban

**Comment by fniephaus** [comment] 2017-07-09 03:46
Closed by 286e0f2e631418b5de7c20d161e1ee990be059b1.

Also, I can confirm that there's no need to install any additional dependencies on Travis to run an OpenSmalltalkVM/PharoVM :)

**Closed by fniephaus** 2017-07-09 03:46 UTC
Labels: Pharo
